#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function replace-vim-file {
  if [ -e ~/$1 ]; then
    mv -f ~/$1 ~/$1.old
  fi
  ln -s $SCRIPT_DIR/$2 ~/$1
}

replace-vim-file .vim
replace-vim-file .vimrc vimrc
replace-vim-file .gvimrc gvimrc

git submodule update --init --quiet

