#!/bin/bash

if [ -z $1 ]; then
  echo "Usage: $0 <plugin-name>"; exit 1
fi

REPO=$1
REPO_PATH=bundle/$REPO

if [ ! -d $REPO_PATH ]; then
  echo "Plugin $REPO is not installed!"
  exit 1
fi

rm -rf $REPO_PATH
git rm $REPO_PATH
git commit -m "Remove the $REPO plugin."
echo "$REPO_PATH removed"
