#!/usr/bin/env bash

function usage {
  echo "Usage: $0 <plugin-repo-url>"; exit 1
  echo "Example: "
  echo "    ./plugin-add https://github.com/gmarik/Vundle.vim.git"
}

if [ -z $1 ]; then
  usage
fi

if [ ! -d bundle ]; then
  mkdir bundle
fi

REPO=`basename $1`
if [[ "$REPO" =~ ".git" ]]; then
  REPO=${REPO%%.*}
fi
REPO_PATH=bundle/$REPO

if [ -d $REPO_PATH ]; then
  echo "The $REPO plugin is already installed!"
  usage
  exit 1
fi

git submodule add $1 $REPO_PATH
git --git-dir $REPO_PATH/.git pull origin master
git add $REPO_PATH
git commit -m "Added $1 to $REPO."
