#!/bin/bash

curl -Sso autoload/pathogen.vim https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim
git submodule update --init --quiet

for d in `ls bundle`; do
  git --git-dir bundle/$d/.git pull origin master
done
